name: Exécuter BahatiBot chaque jour

on:
  schedule:
    - cron: '0 12 * * *'  # Tous les jours à midi UTC
  workflow_dispatch:      # Permet un lancement manuel

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Configurer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Installer les dépendances Python
        run: |
          pip install pywikibot language-tool-python

      - name: Lancer BahatiBot
        env:
          BOT_PASSWORD: ${{ secrets.BOT_PASSWORD }}
        run: |
          python bahati_bot.p
